# Generated by scripts/seed_regen — do not edit.
# Regenerate with: make -C data regen

SEED_MANIFEST_OUTPUTS := \
  accounts.json \
  parties.json \
  party_match_patterns.json \
  ledger_settings.json \
  cel_rule_sets.json \
  import_templates.json \
  journal_entry_filter_presets.json \
  cheque_register_filter_presets.json \
  metadata.json

accounts.json: seed_data.tar.gz
parties.json: seed_data.tar.gz
party_match_patterns.json: seed_data.tar.gz
ledger_settings.json: seed_data.tar.gz
cel_rule_sets.json: seed_data.tar.gz
import_templates.json: seed_data.tar.gz
journal_entry_filter_presets.json: seed_data.tar.gz
cheque_register_filter_presets.json: seed_data.tar.gz
metadata.json: seed_data.tar.gz
